version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"  
  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/my-config.yml --name nakama1 --database.address postgres:localdb@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100         
    restart: always
    links:
      - "postgres:db"
    depends_on:
      - postgres    
    volumes:
      - ./nakama_data/:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: jonasal/nginx-certbot:latest
    environment:
      CERTBOT_EMAIL: "stephan.kessler@outlook.com"
    ports:
      - "80:80"
      - "443:443"
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
      - ./nginx_conf.d:/etc/nginx/user_conf.d
    links:
      - nakama
    depends_on:
      - nakama
volumes:
  data:
