name: Setup the client for exports
description: |
  this will create folders and change the different places where
  the version must be inserted

runs:
  using: composite
  steps:
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      shell: bash
    - name: Replace version string
      env:
        VERSION_REGEX: "<VERSION>"
      shell: bash
      run: |
        VERSION=${GITHUB_REF_NAME}
        # In the case it's not a new tag, we use the commit sha
        if [ "$GITHUB_REF_TYPE" == 'branch' ]; then
          VERSION=${GITHUB_SHA:0:7}
        fi
        sed -i "s|$VERSION_REGEX|$VERSION|g" client/levels/menu.tscn # Replace the literal string '<VERSION>' with the new constant declaration
        sed -i "s|$VERSION_REGEX|$VERSION|g" client/project.godot # Replace the literal string '<VERSION>' with the new constant declaration
    - name: Pre create/import everything
      shell: bash
      run: |
        mkdir -v -p build/windows
        mkdir -v -p build/linux
        mkdir -v -p build/web
        mkdir -v -p build/mac
        cd $PROJECT_PATH
        godot --project . --headless --import -e 2>/dev/null
