name: "gd script validations"
on:
  pull_request:
    branches: [ "master" ]
    paths:
      - ".github/workflows/gd-type-check.yaml"
      - 'client/**'
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/gd-type-check.yaml"
      - 'client/**'

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: codename-recon
  PROJECT_PATH: codename-recon

jobs:
  type-check:
    name: Check the types in the project
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Run checks
        run: |
          cd client
          set +e
          godot --project . --headless --quit-after 100 -e 2>/dev/null
          godot --project . --headless --quit 2>&1 | grep SCRIPT -A 1 > ./test_err
          COUNT=$(wc -l test_err)
          if [ "$COUNT" != "0 test_err" ]; then 
            cat test_err
            exit 1
          else
            echo "It worked, is green, everything should be fine!"
            exit 0
          fi

  export:
    name: Export plattform binaries
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    
    steps:
      # - name: Create godot caches
      #   run: |
      #     cd client
      #     set +e
      #     godot --project . --headless --quit-after 100 -e 2>/dev/null
      
      - name: Export linux
        run: |
          pwd
          mkdir -v -p export/desktop/linux
          godot -v --headless --export-release "Linux/X11" ./export/desktop/linux/$EXPORT_NAME.x86_64

      - name: Export windows
        run: |
          mkdir -v -p export/desktop/windows
          godot -v --headless --export-release "Windows Desktop" ./export/desktop/windows/$EXPORT_NAME.exe

      - name: Export mac-os
        run: |
          mkdir -v -p export/desktop/mac
          godot -v --headless --export-release "Mac OSX" ./export/desktop/mac/$EXPORT_NAME.zip

      - name: Export html
        run: |
          mkdir -v -p export/html
          godot -v --headless --export-release "HTML5" ./export/html/index.html
          zip -r html.zip export/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exports
          path: |
            ./export/desktop/linux/$EXPORT_NAME.x86_64
            ./export/desktop/windows/$EXPORT_NAME.exe
            ./export/desktop/mac/$EXPORT_NAME.zip
            ./export/html/html.zip